### ISSUE TITLE
List of potential things to do

### ISSUE THREAD

**Issue by rowlandm** [WEHI-ResearchComputing/student-intern-organiser#1]
#Application Stage
- ~~ Fill out form including upload pdf ~~
- ~~ Email acknowledgement ~~
- Create initial review with ability to highlight text and rate atttributes overall along with a recommendation

#Allocation and Management Stage
- ~~View all students with status and filter and sort~~
- ~~View one student with all details~~
- ~~Create a summary report to send to other supervisors~~
- ~~Make it easy to start allocating people to projects~~
- Email offer email that is appropriate with details about start and end dates and other things
- Is there a way to easily edit and sign a contract pdf and send it within the application?
- ~~Upload and save the contract pdf~~
- ~~Ability to update a student or multiple student status~~
- ~~Email signed contract and application and details to Maria in bulk or one at a time.~~ This should update the status.
- ~~Ability to email in bulk to all students or email to specific students~~
- Ability to close student form for Bachelor of Science / Data Science separate to Engineering
- Email the rejection letter with data analytics.

#Internship Stage
- ~~Set scheduled emails based on start and end dates and week number~~
- Help organise presentations somehow and have that integrated?

#Finalise and Beyond Stage
- ~~Ability to rate interns after their internship has finished. Ability to send this out.~~
- ~~Calculate amounts of previous and current students~~

**Comment by richarddushime** [comment]
Hi @rowlandm 
i would like to contribute to this project but after  setting up the project there is some files missing student_intern_data/student_intern_data.db etc..   which are needed for the project to run smoothly 
if possible to upload and push them i will be happy to contribute to this amazing project
 currently i only improved the Readme file on the installation process i added for windows

**Comment by rowlandm** [comment]
This is where the public data for testing could be stored....

**Comment by rowlandm** [comment]
It now has all the data from the main database now, but with simple student data...
