### ISSUE TITLE
Update emails to students to highlight remote and to not go onsite first day

### ISSUE THREAD

**Issue by rowlandm** [WEHI-ResearchComputing/student-intern-organiser#19]
Want to add this below email (in a shorter form) as part of the "1 week before" and "this is your first week" email.

Hi All,

Apologies for the confusion but a couple of people thought they needed to be onsite this morning but this is inaccurate. This is a 100% remote internship.

The confusion came due to a Workday email that says "On your first day, please arrive at 9.00am unless your manager has advised an alternative time and ask for your manager upon arrival at reception." - this part of the email can be ignored.

For those in Science, you can start your internship today, but we are flexible. For Engineering IT students, you can start your internship next week the 20th of November, but we are flexible if you want to start it later.

Apologies again for the confusion.

I have also updated the FAQ here https://wehi-researchcomputing.github.io/faq

**Comment by Xenotion** [comment]
How are you sending this email currently?

**Comment by rowlandm** [comment]
This has been done.
