### ISSUE TITLE
Remove 11 - Added to WEHI-wide Teams Group

### ISSUE THREAD

**Issue by rowlandm** [WEHI-ResearchComputing/student-intern-organiser#27]
As of Intake 9, Semester 1 2024, I will not be adding student unimelb emails to the WEHI-wide Teams Group.

Therefore we can make this "11 - N/A" to keep the status but leave it "blank".

**Comment by Xenotion** [comment]
This would require direct modification onto the prod database under "Statuses" table. 

Currently any modification made to the fake database is not committed as it's part of .gitignore file. 

I can go ahead and just Update this table if needed.

**Comment by rowlandm** [comment]
That is fine, but we do need to update the data in https://github.com/WEHI-ResearchComputing/student_intern_data_public to be consistent.
