### ISSUE TITLE
Breakdown in dashboard by pronouns

### ISSUE THREAD

**Issue by rowlandm** [WEHI-ResearchComputing/student-intern-organiser#3]
(venv) mac3497:student_intern_data mosbergen.r$ sqlite3 student_intern_data.db "SELECT pronouns, COUNT(pronouns) FROM Students WHERE status LIKE '%09%' OR status LIKE '%10%' OR status LIKE '%14%' OR status LIKE '%08%' GROUP BY pronouns;"

**Comment by rowlandm** [comment]
sqlite3 student_intern_data.db "SELECT pronouns, course, COUNT(pronouns) FROM Students WHERE status LIKE '%09%' OR status LIKE '%10%' OR status LIKE '%14%' OR status LIKE '%08%' GROUP BY pronouns, course;"

**Comment by rowlandm** [comment]
Hi @richarddushime - this might be a good, easy one for you.

This is to calculate the breakdown of students by pronoun across the student cohorts 

This includes statuses of

09

**Comment by richarddushime** [comment]
Okay , Thanks . working on it 

> Hi @richarddushime - this might be a good, easy one for you.
> 
> This is to calculate the breakdown of students by pronoun across the student cohorts
> 
> This includes statuses of:
> 
> 09 Signed contract 10 Sent to be added to Workday 11 Added to WEHI-wide Teams Group 12 WEHI email created 13 Internship started 14 Finished
> 
> See the sql above for more details.

**Comment by rowlandm** [comment]
Ok, let's step back.

I want to do a breakdown of the pronouns on the dashboard view.

It will add to the current data shown already in the dashboard.

It will be in another table similar to the other data shown.

It should look like this

she/her 55
he/him 54

And the data should be based on a subset of statuses. These statuses are the ones that show that students have been through the internship before it are currently going through the internship, or will go in the future.


09 Signed contract
10 Sent to be added to Workday
11 Added to WEHI-wide Teams Group
12 WEHI email created
13 Internship started
14 Finished

So not all students will be shown, just the ones that have this status.

To confirm we are both understanding the same thing, can you please take a screenshot of the current dashboard and add text to the screenshot image to show what this might look like once you finished please?

This will help us agree.

Thanks again for your enthusiasm.

**Comment by rowlandm** [comment]
This has been done in https://github.com/WEHI-ResearchComputing/student-intern-organiser/pull/8
