### ISSUE TITLE
Change Status, Change Project, Change Rating button not working

### ISSUE THREAD

**Issue by Xenotion** [WEHI-ResearchComputing/student-intern-organiser#33]
Might be local development/database issue, but none of the 'Change Status', 'Change Project', or 'Change Rating' buttons actually update the student info. 

Sends a POST request with code 302 and GET request with 200 but no changes are reflected.

**Comment by rowlandm** [comment]
I just tested this and it seems to be working. I have to refresh the website to see the changes though.

**Comment by Xenotion** [comment]
Turns out the change is reflected when I refresh the website
