### ISSUE TITLE
Allocate Students to Project button not working in New Intakes All page

### ISSUE THREAD

**Issue by Xenotion** [WEHI-ResearchComputing/student-intern-organiser#39]
@rowlandm 

As mentioned in the title

http://127.0.0.1:5000/assigned_projects/ 
gives 
{"message":"'in <string>' requires string as left operand, not NoneType","status":"error"}

**Comment by rowlandm** [comment]
I had this error in my production database when I added two new students. I am not sure why but it is based on students.  

One by one I changed the status of new students to "15 Applied after close" so they didn't come up in that view. I then figured out that the last two students I added had caused the problem.

**Comment by rowlandm** [comment]
Ahhh - I think this is because you have data that doesn't make sense.

I think you will find that it is because the overall internal isn't set and needs to be displayed. 

Usually by quick review, these fields would be updated.

**Comment by rowlandm** [comment]
This has been solved as part of commit 5976e57a6fc056c6e6a6163ba04c67ac3a527c5c
