### ISSUE TITLE
Post Internship Student review

### ISSUE THREAD

**Issue by rowlandm** [WEHI-ResearchComputing/student-intern-organiser#9]
It would be nice to replicate this spreadsheet - where you can review the student to give them feedback.

https://docs.google.com/spreadsheets/d/1f4gR55bqIAkFZA5QJLi0IahBQB-ZBbixCWGKDB0p_4E/edit?usp=sharing

Mapping from sqlite to Standardised Vocabulary tab:

- post_internship_adaptability | Column A
- post_internship_learn_technical | Column B
- post_internship_learn_conceptual | Column C
- post_internship_collaborative | Column D
- post_internship_ambiguity | Column E
- post_internship_complexity | Column F
- post_internship_summary_rating_external | Column G

**Comment by rowlandm** [comment]
Excellent work Richard!

**Comment by richarddushime** [comment]
> Excellent work Richard!

Thank you 🥇
